export const projectDataOne = [
    {
        shortName: "shoestring",
        name: "The Shoestring Traveller",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/the-shoestring-traveller_etc1bk.png",
        description: "Travel website featuring articles on amazing destinations around the world.",
        about: "Travel website where users can sign in to favourite and comment on travel articles.",
        technologies: ["React", "Node.js", "Express.js", "MongoDB"],
        website: "https://theshoestringtraveller.matthewlangmuir.com",
        demo: "https://www.youtube.com/watch?v=0gZP3fPHipo&t=326s&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/the-shoestring-traveller",
    },
    {
        shortName: "slingair",
        name: "slingAir",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/slingair_ntda0j.png",
        description: "Airline ticket booker that allows users to book one of eight flights from Canadian cities to Honolulu.",
        about: "",
        technologies: ["React", "Node.js", "Express.js", "MongoDB"],
        demo: "https://www.youtube.com/watch?v=iyu7ZcsxeZs&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/slingair-ticket-booker",
    },
    {
        shortName: "facespace",
        name: "Facespace",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745379/Portfolio/facespace_uflefj.png",
        description: "Social networking application with a simple sign-in function.",
        about: "",
        technologies: ["React", "Node.js", "Express.js"],
        demo: "https://www.youtube.com/watch?v=NvgMKt3NJ0c&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/facespace",
    },
    {
        shortName: "tutoring",
        name: "Matthew Langmuir Tutoring",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/matthew-langmuir-tutoring_i2zzw0.png",
        description: "Classroom website that gives English students access to assignments and readings.",
        about: "Created with React with URL params to create the Course Materials page and used The EmailJS API is used for the Contact page, which students can use to ask  homework questions.",
        technologies: ["React"],
        website: "https://www.tutoring.matthewlangmuir.com/",
        github: "https://github.com/mlangmuir/matthew-langmuir-tutoring",
    },
]

export const projectDataTwo = [
    {
        shortName: "shopfit",
        name: "Shopfit",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/shopfit_mtynmn.png",
        description: "Electronic gadgets e-commerce website.",
        about: "This full-stack application allows users to use a search bar to search 348 different products and filter these products based on price, category, body location and availability.",
        technologies: ["React", "Node.js", "Express.js", "MongoDB"],
        demo: "https://www.youtube.com/watch?v=fYlcX2Ul3h0&t=1s&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/shopfit-e-commerce",
    },
    {
        shortName: "critter",
        name: "Critter",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/critter_qndgst.png",
        description: "Cat-themed Twitter clone.",
        about: "This React application allows user to send tweets (or meows) and navigate to the profiles of different cats.",
        technologies: ["React"],
        demo: "https://www.youtube.com/watch?v=H6wl6lcQYi8&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/critter-cat-twitter-clone",
    },
    {
        shortName: "nyan-cats",
        name: "Raining Nyan Cats",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/raining-nyan-cats_oilyl5.png",
        description: "JavaScript browser game.",
        about: "A browser game based on the Internet meme Nyan Cat. The game involves the user using the left and right arrow keys to move a burger and try to avoid the cats that are falling from the top of the screen.",
        technologies: ["JavaScript", "HTML", "CSS"],
        website: "https://rainingnyancats.matthewlangmuir.com/",
        github: "https://github.com/mlangmuir/raining-nyan-cats-game",
    }
]
