export const projectData = [
    {
        column: 1,
        shortName: "shoestring",
        name: "The Shoestring Traveller",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/the-shoestring-traveller_etc1bk.png",
        description: "Travel website featuring articles on amazing destinations around the world.",
        about: "This travel website features articles about the Shoestring Traveller's adventures around the world. It includes some budget travel tips and numerous breathtaking photos. The app also allows users to log in and comment on their favourite articles.",
        technologies: ["React", "Node.js", "Express.js", "MongoDB"],
        demo: "https://www.youtube.com/watch?v=0gZP3fPHipo&t=326s&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/the-shoestring-traveller",
    },
    {
        column: 1,
        shortName: "slingair",
        name: "slingAir",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/slingair_ntda0j.png",
        description: "Airline ticket booker concept.",
        about: "This ticket booking app allows users to book one of eight flights from Canadian cities to Honolulu. For each booking, the availability of the seats gets updated and recorded in the database so no seat gets booked twice!",
        technologies: ["React", "Node.js", "Express.js", "MongoDB"],
        demo: "https://www.youtube.com/watch?v=iyu7ZcsxeZs&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/slingair-ticket-booker",
    },
    {
        column: 1,
        shortName: "facespace",
        name: "Facespace",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745379/Portfolio/facespace_uflefj.png",
        description: "Social networking application concept.",
        about: "This is a social networking application with a simple sign-in function. It uses session storage to keep the user logged in while they are using the application.",
        technologies: ["React", "Node.js", "Express.js"],
        demo: "https://www.youtube.com/watch?v=NvgMKt3NJ0c&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/facespace",
    },
    {
        column: 1,
        shortName: "tutoring",
        name: "Matthew Langmuir Tutoring",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/matthew-langmuir-tutoring_i2zzw0.png",
        description: "Classroom website that gives English students access to assignments and readings.",
        about: "This React application allows students to access their course material and contact the instructor via the Contact page.",
        technologies: ["React"],
        website: "https://www.tutoring.matthewlangmuir.com/",
        github: "https://github.com/mlangmuir/matthew-langmuir-tutoring",
    },
    {
        column: 2,
        shortName: "shopfit",
        name: "Shopfit",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/shopfit_mtynmn.png",
        description: "E-commerce website concept.",
        about: "This full-stack application allows users to browse through 348 different electronic gadgets. The site features a search bar and allows users to filter products based on price, category, body location and availability.",
        technologies: ["React", "Node.js", "Express.js", "MongoDB"],
        demo: "https://www.youtube.com/watch?v=fYlcX2Ul3h0&t=1s&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/shopfit-e-commerce",
    },
    {
        column: 2,
        shortName: "critter",
        name: "Critter",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/critter_qndgst.png",
        description: "Cat-themed Twitter website concept.",
        about: "This React application allows user to send tweets (or meows) and navigate to the profiles of different cats.",
        technologies: ["React"],
        demo: "https://www.youtube.com/watch?v=H6wl6lcQYi8&ab_channel=MatthewLangmuir",
        github: "https://github.com/mlangmuir/critter-cat-twitter-clone",
    },
    {
        column: 2,
        shortName: "nyan-cats",
        name: "Raining Nyan Cats",
        imgSrc: "https://res.cloudinary.com/didxdrmjj/image/upload/v1663745378/Portfolio/raining-nyan-cats_oilyl5.png",
        description: "JavaScript browser game.",
        about: "A browser game based on the Internet meme Nyan Cat. The game involves the user using the left and right arrow keys to move a burger and try to avoid the cats that are raining down from the top of the screen.",
        technologies: ["JavaScript", "HTML", "CSS"],
        website: "https://rainingnyancats.matthewlangmuir.com/",
        github: "https://github.com/mlangmuir/raining-nyan-cats-game",
    }
]